export const TEST = 'TEST';
export const SET_VA = 'SET_VA';
export const CREATE_MEETING_VA = "CREATE_MEETING_VA";
export const CREATE_MEETING_VA_SUCCESS = "CREATE_MEETING_VA_SUCCESS";
export const CREATE_MEETING_VA_FAILURE = "CREATE_MEETING_VA_FAILURE";
