// export const LOGIN_USER = 'LOGIN_USER';
export const SET_SESSION = 'SET_SESSION';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_LOGIN_CREDENTIALS = 'SET_LOGIN_CREDENTIALS';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';