export const SET_FETCH_MEETINGS = 'SET_FETCH_MEETINGS';
export const SET_MEETING_SUMMARY_DATA = 'SET_MEETING_SUMMARY_DATA';
export const SET_FETCH_PAST_MEETINGS = 'SET_FETCH_PAST_MEETINGS';
export const SET_FETCH_UPCOMING_MEETINGS = 'SET_FETCH_UPCOMING_MEETINGS';
// export const SET_FETCH_TODAY_MEETINGS = 'SET_FETCH_TODAY_MEETINGS';